### ISSUE TITLE
source code of image

### ISSUE THREAD

**Issue by ramilexe** [CircleCI-Public/android-image-preview-docs#11]
Hello, is it possible to get the source of this docker image `android:202102-01`?

Thanks

**Comment by lokst** [comment]
@ramilexe Thank you for your interest in this image. However, this is not a Docker image, so we don't have a Dockerfile for this. This is a Linux VM image that runs with our [Linux machine executor](https://circleci.com/docs/2.0/executor-types/#using-machine).

**Comment by ramilexe** [comment]
Hi @lokst 
Thank you for the response. Can I take a look at some "source code" of this Linux VM?

**Comment by lokst** [comment]
@ramilexe Unfortunately, the repository we use to build the image is not yet open-sourced. However, if you have any questions about the image I'll be happy to answer 🙂
