### ISSUE TITLE
Global NPM Config removes the default NPM CA

### ISSUE THREAD

**Issue by impleri** [CircleCI-Public/android-image-preview-docs#14]
One of my jobs started failing late last week with a certificate issue. After using the SSH option, I found out the global NPM config was indeed breaking the default CA.
```
$ npm config list
; "global" config from /opt/circleci/.nvm/versions/node/v14.16.0/etc/npmrc

ca = [""] 
```
Unsetting that value (`npm config delete ca`) did indeed fix the issue.

**Comment by lokst** [comment]
@impleri Thank you for the report! Would you mind sharing what part of the job or what command was failing?

**Comment by impleri** [comment]
The step had one command: `npm install -g detox-cli`

And the error in NPM was:
```
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/detox-cli failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-03-08T16_30_11_114Z-debug.log
```

**Comment by lokst** [comment]
@impleri Thank you for sharing the command and error!

**Comment by donatoaguirre24** [comment]
Hi guys, I'm experiencing the same issue. Is there any workaround I can use until you release the fix?

**Comment by lokst** [comment]
This issue will be fixed soon ,  but those who need a workaround in the meantime can run this:

```
npm config -g delete ca
```

**Comment by lokst** [comment]
This issue was closed prematurely due to automation, but is now truly resolved!
