### ISSUE TITLE
Request: Git LFS

### ISSUE THREAD

**Issue by eddieSullivan** [CircleCI-Public/android-image-preview-docs#16]
Hi, and thank you for providing this image. It would be helpful for our use case if it came with git-lfs installed.
Thanks!

**Comment by FelicianoTech** [comment]
Hi. This repository is no longer used thus I am archiving it and closing all issues.

This particular issue, I'd like to let you know I've added it to our internal tracker. We're aiming to have the Android VM image include git-lfs for the February release.
