### ISSUE TITLE
Does android-machine-image support the on-premise version?

### ISSUE THREAD

**Issue by hung-cybo** [CircleCI-Public/android-image-preview-docs#17]
There is no info about the supported edition.

So, Does android-machine-image support the on-premise version?

My Current version
CircleCI Server: 2.19.12
Supported syntax version: 2.0

The error when I tried to build on CI:

```
Build-agent version 1.219.48216-fe3742fa (2020-12-09T13:47:53+0000)
Creating a dedicated VM with android:202102-01 image
failed to create host: Image android:202102-01 is not supported

failed to create host: Image android:202102-01 is not supported
```

Thank you in advance.

**Comment by FelicianoTech** [comment]
Hi. I'm don't think I know the answer to that but please open a ticket with your account manager /CircleCI Support to bring this question up.

This entire repository is being archived so I am going to close the issue here.
