### ISSUE TITLE
Request: yarn

### ISSUE THREAD

**Issue by fotos** [CircleCI-Public/android-image-preview-docs#19]
## Description

The machine image includes `node`, but lacks `yarn`:

```
circleci@default-b7fcaf69-e9d1-4313-9ca0-bc79b5bcde9f:~/project$ yarn

Command 'yarn' not found, but can be installed with:

apt install cmdtest
Please ask your administrator.
```

Both the new `cimg/android` and the legacy `circleci/android` docker images include `yarn`.

From the [legacy `circleci/android`](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/android/images/api-30-node/Dockerfile#L260-L279) convenient image:

```
$ docker run --rm -ti circleci/android:api-30-node yarn --version
1.22.5
```

The [newer `cimg/android`](https://github.com/CircleCI-Public/cimg-android/blob/release-v2022.01.1/2022.01/node/Dockerfile#L15-L20) image:

```
$ docker run --rm -ti cimg/android:2022.01.1-node yarn --version
1.22.5
```

Having `yarn` installed by default would save time from `npm install --global yarn`. 🙏

**Comment by FelicianoTech** [comment]
Hi. We're tracking this internally. I believe this will be in Android for the February release. Worst case scenario, March.

Thanks.
