### ISSUE TITLE
List of supported tags

### ISSUE THREAD

**Issue by dmitry-ryadnenko-izettle** [CircleCI-Public/android-image-preview-docs#20]
Hi. Looks like `android:2021.01.1' is also supported right now as a machine image. But I can't find anywhere a list of all supported images for Android machine executor. Where can I find one? May be there is some repository I can look at that contains this list?

**Comment by JalexChen** [comment]
Hi @dmitry-ryadnenko-izettle 

You can find a list of available Android Machine Images [here](https://circleci.com/developer/machine/image/android#image-tags)

They should be listed out at the bottom, but looks like it's missing a couple tags. Here is the supported list of tags:
android:202102-01
android:2021.10.1
android:2021.12.1
android:2022.01.1

As for a repository that has all of these listed, I think this is the correct Repository. I'll likely get started on getting everything updated

**Comment by dmitry-ryadnenko-izettle** [comment]
Thank you @JalexChen 🙏
