### ISSUE TITLE
Resource class question

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/android-image-preview-docs#4]
Hey @lokst,

In the sample config we have this section:

```
machine:
      image: android:202102-01
    resource_class: large
```

When I tried this, I couldn't get it to run with resource class large. I was able to specifying a resource class at all. As far as I know  I have that resource class, do you know why I am running into a problem?

**Comment by lokst** [comment]
@felicianotech Could it be an identation issue? You should be able to use resource class `large` with the image

**Comment by lokst** [comment]
Closing this for now but let me know if there is still an issue
