### ISSUE TITLE
Instrumentation run failed due to 'Process crashed.

### ISSUE THREAD

**Issue by mtwalli** [CircleCI-Public/android-image-preview-docs#5]
I tired the image, unfortunately  the tests failed all the time with 
`Tests on test(AVD) - 10 failed: Instrumentation run failed due to 'Process crashed.'`
you can fine more information in this [build](https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-android/9307/workflows/5d124eb7-f05b-42a9-bf2b-5731ef9725c3/jobs/52259)

Do you have any idea what could be the reason?

BTW ,tests run locally using Android studio successfully

**Comment by lokst** [comment]
@mtwalli Thanks for reporting the issue, I'll take a look at it

**Comment by lokst** [comment]
@mtwalli I tried running `/gradlew connectedDeviceForTestersDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=testhelpers.Screenshot` locally but had similar errors: 

```
de.rki.coronawarnapp.ui.submission.SubmissionDispatcherFragmentTest > testEventQRClicked[Pixel_2_Android_10(AVD) - 10] FAILED
        androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 539, 1575 and precision: 16, 16' on view 'Animations or transitions are enabled on the target device.
        For more info check: https://developer.android.com/training/testing/espresso/setup#set-up-environment

de.rki.coronawarnapp.ui.submission.SubmissionTanFragmentTest > testEventTanNextClicked[Pixel_2_Android_10(AVD) - 10] FAILED
        androidx.test.espresso.PerformException: Error performing 'scroll to' on view 'Animations or transitions are enabled on the target device.
        For more info check: https://developer.android.com/training/testing/espresso/setup#set-up-environment
Tests on Pixel_2_Android_10(AVD) - 10 failed: Instrumentation run failed due to 'Process crashed.'
```

Could you share the command arguments you used to create the AVD and launch the emulator when you ran the tests succesfully?

**Comment by mtwalli** [comment]
@lokst what you are experiencing is different. it is failing for you because the device (or emulator) animations are enabled.
it is recommended to disable them before running the UI tests.
You can do this either from the command line as follows:
``` 
adb shell settings put global window_animation_scale 0.0
adb shell settings put global transition_animation_scale 0.0
adb shell settings put global animator_duration_scale 0.0
```
or from [` Developer options` ](https://developer.android.com/training/testing/espresso/setup#set-up-environment)

**Comment by lokst** [comment]
@mtwalli Could you take a look at my PR?

**Comment by mtwalli** [comment]
@lokst  I checked and it is working successfully.
Thank you very much!

**Comment by lokst** [comment]
Closing this, thanks for the verification @mtwalli !
