### ISSUE TITLE
Is there any way to change emulator configurations?

### ISSUE THREAD

**Issue by mtwalli** [CircleCI-Public/android-image-preview-docs#6]
Test emulator has the following properties by default
```
  hw.lcd.width = 320
  hw.lcd.height = 640
  hw.lcd.depth = 16
  hw.lcd.density = 160
```

for our project we use the emulator to take Screenshots. With the properties mentioned above, Screenshots will have low resolution. is it possible to change these configs?

Our project is open-source you can have a look [here](https://github.com/corona-warn-app/cwa-app-android/blob/main/.circleci/config.yml#L132-L135)

**Comment by lokst** [comment]
@mtwalli You should be able to make similar changes to the config.ini file at `$HOME/.android/avd/<AVD_NAME>.avd/config.ini`  , for example, `$HOME/.android/avd/test.avd/config.ini`

**Comment by mtwalli** [comment]
Perfect , 👌 Thanks for the info
