### ISSUE TITLE
Instrumentation test sometimes failed to run to completion . 

### ISSUE THREAD

**Issue by Dai1678** [CircleCI-Public/android-image-preview-docs#7]
I tried this image `android:202102-01`, unfortunately `./gradlew connectedDebugAndroidTest` sometimes failed.
(resource_class use `xlarge`)

In this failure test, using `ActivityScenario#launch` and `ActivityScenario#onActivity`.

Error code is here.
```
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 6 tests, received 1'. Check device logcat for details
Tests on test(AVD) - 10 failed: Test run failed to complete. Expected 6 tests, received 1. onError: commandError=false message=INSTRUMENTATION_ABORTED: System has crashed.
```

Anyone has solution ?
Tests run locally using Android studio successfully.

**Comment by lokst** [comment]
@Dai1678 Thanks for filing the issue, I'll look into it and get back to you

**Comment by lokst** [comment]
Adding a step after the emulator has booted up may provide more clues to the cause of the error

```
- run:
     name: Logcat
     command: |
       adb logcat
     background: true
```

However it could also be due to an issue with the emulator, as I note that it looks a little similar to https://issuetracker.google.com/issues/159732638 

I would recommend adding some retry logic to the tests in the meantime. Here is an example: https://github.com/CircleCI-Public/android-image-preview-docs#using-the-android-machine-image

**Comment by Dai1678** [comment]
Thanks for seeing my comment @lokst !

I'll try to include the log output and retry logic in the step as you suggested.

**Comment by Dai1678** [comment]
FYI, this is failure test code.
`billingRepository.launchBillingFlow` called  `BillingClient#launchBillingFlow(Activity, BillingFlowParams)`

```
  @Test
  fun clearPurchaseState() {
    val scenario = launchActivity<TestActivity>()
    scenario.onActivity { activity ->
      coEvery { officeRepository.officeShow() } returns flowOf(officeShow)
      coEvery { billingRepository.launchBillingFlow(activity, skuDetails) } returns flowOf(purchase)
      val viewModel = PremiumPlanViewModel(officeRepository, billingRepository)
      val purchaseStateValueHistory = viewModel.purchaseState
        .test()
        .valueHistory()

      viewModel.purchase(skuDetails, activity)

      // before
      Assert.assertTrue(purchaseStateValueHistory.first().isLoading)
      Assert.assertEquals(purchaseStateValueHistory[1].getValueOrNull(), purchase)
      Assert.assertEquals(purchaseStateValueHistory.count(), 2)

      viewModel.clearPurchaseState()

      // after
      Assert.assertNull(purchaseStateValueHistory[2].getValueOrNull())
    }
    scenario.close()
  }
```

**Comment by lokst** [comment]
@Dai1678 Thank you for the information. Is it consistently the same test case that fails with this error?

I wonder if switching to a different system image, e.g. `system-images;android-29;default;x86_64`  or `system-images;android-29;default;x86` helps?

I think it would be good to disable animations after the emulator has started up too:

```
- run:
          name: Disable emulator animations
          command: |
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
```

**Comment by Dai1678** [comment]
@lokst 
Thanks for the suggestion!
The error is happening in the same test case.
I will try the sample code first.

I'll close this issue and #8 .
